# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

"""
1. service.proto (La Definizione)
È il file sorgente scritto in IDL (Interface Definition Language). Qui definisci "cosa" il servizio può fare 
(i metodi checkUser o delete_interestes_by_email) e "quali" dati scambiare.

2. service_pb2.py (L'interfaccia dei Dati)
Questo file viene generato dal compilatore protoc e contiene le classi Python corrispondenti ai messaggi definiti 
nel .proto (come UserCheckMessage o UserResponse).

A cosa serve: Fornisce i metodi per serializzare e leggere i dati in formato binario (Protocol Buffers). 
Senza questo file, il tuo codice non saprebbe come "impacchettare" le informazioni da spedire sulla rete.

3. service_pb2_grpc.py (L'interfaccia di Comunicazione)
Anche questo è generato automaticamente e contiene la logica per la chiamata remota vera e propria.

Lo Stub (Client): Fornisce l'oggetto locale che il client chiama come se fosse una funzione normale. 
Quando chiami un metodo sullo stub, questo file si occupa di inviare la richiesta al server.

Il Servicer (Server): Fornisce la classe base (lo "scheletro") che il server deve ereditare e implementare 
per rispondere alle chiamate.
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"!\n\x10SendEmailMessage\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"0\n\x10UserCheckMessage\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\"/\n\x0cUserResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t2|\n\x0bUserService\x12-\n\tcheckUser\x12\x11.UserCheckMessage\x1a\r.UserResponse\x12>\n\x1a\x64\x65lete_interestes_by_email\x12\x11.SendEmailMessage\x1a\r.UserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENDEMAILMESSAGE']._serialized_start=17
  _globals['_SENDEMAILMESSAGE']._serialized_end=50
  _globals['_USERCHECKMESSAGE']._serialized_start=52
  _globals['_USERCHECKMESSAGE']._serialized_end=100
  _globals['_USERRESPONSE']._serialized_start=102
  _globals['_USERRESPONSE']._serialized_end=149
  _globals['_USERSERVICE']._serialized_start=151
  _globals['_USERSERVICE']._serialized_end=275
# @@protoc_insertion_point(module_scope)
