apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-system
spec:
  #replicas: 1
  selector:
    matchLabels:
      app: alert-system
  template:
    metadata:
      labels:
        app: alert-system
    spec:
      containers:
        - name: alert-system
          image: alert_system:latest
          imagePullPolicy: Never
          command: ["python", "AlertSystem.py"]
          ports:
            - containerPort: 9999
          env:
            - name: DB_HOST
              value: "mysql-service"
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"
          readinessProbe:
            tcpSocket:
              port: 9999
            initialDelaySeconds: 5
            periodSeconds: 10

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier-system
spec:
  #replicas: 1
  selector:
    matchLabels:
      app: notifier-system
  template:
    metadata:
      labels:
        app: notifier-system
    spec:
      containers:
        - name: notifier-system
          image: notifier_system:latest
          imagePullPolicy: Never
          command: ["python", "AlertNotifierSystem.py"]
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"