# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.checkUser = channel.unary_unary(
                '/UserService/checkUser',
                request_serializer=service__pb2.UserCheckMessage.SerializeToString,
                response_deserializer=service__pb2.UserResponse.FromString,
                _registered_method=True)
        self.sendInterests = channel.unary_unary(
                '/UserService/sendInterests',
                request_serializer=service__pb2.UserInterestsMessage.SerializeToString,
                response_deserializer=service__pb2.UserResponse.FromString,
                _registered_method=True)
        self.getInfoByAirport = channel.unary_unary(
                '/UserService/getInfoByAirport',
                request_serializer=service__pb2.UserInterestsMessage.SerializeToString,
                response_deserializer=service__pb2.FlightsInfo.FromString,
                _registered_method=True)


class UserServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def checkUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sendInterests(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getInfoByAirport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'checkUser': grpc.unary_unary_rpc_method_handler(
                    servicer.checkUser,
                    request_deserializer=service__pb2.UserCheckMessage.FromString,
                    response_serializer=service__pb2.UserResponse.SerializeToString,
            ),
            'sendInterests': grpc.unary_unary_rpc_method_handler(
                    servicer.sendInterests,
                    request_deserializer=service__pb2.UserInterestsMessage.FromString,
                    response_serializer=service__pb2.UserResponse.SerializeToString,
            ),
            'getInfoByAirport': grpc.unary_unary_rpc_method_handler(
                    servicer.getInfoByAirport,
                    request_deserializer=service__pb2.UserInterestsMessage.FromString,
                    response_serializer=service__pb2.FlightsInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('UserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def checkUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserService/checkUser',
            service__pb2.UserCheckMessage.SerializeToString,
            service__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def sendInterests(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserService/sendInterests',
            service__pb2.UserInterestsMessage.SerializeToString,
            service__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getInfoByAirport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserService/getInfoByAirport',
            service__pb2.UserInterestsMessage.SerializeToString,
            service__pb2.FlightsInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
